#!/usr/bin/env ruby
require_relative 'app'
require_relative 'user_interface'

class Main
  def initialize
    @app = App.new
    @user_interface = UserInterface.new
  end

  def run
    @user_interface.display_welcome_message

    loop do
      @user_interface.display_options

      option = @user_interface.get_user_input

      case option
      when '1'
        @app.all_books
      when '2'
        @app.all_people
      when '3'
        @app.create_person
      when '4'
        @app.create_book
      when '5'
        @app.create_rental
      when '6'
        @app.all_rentals
      when '7'
        break
      else
        @user_interface.display_invalid_option
      end
    end
  end
end

Main.new.run
